UnitOfWorkSample/Models/RestaurantViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DataAccess;
using System.IO;
using UnitOfWorkSample.Helpers;
using System.ComponentModel.DataAnnotations;

namespace UnitOfWorkSample.Models
{
    /// <summary>
    /// The ViewModel class for the Index.cshtml, Details.cshtml and Edit.cshtml
    /// Usually we have to use always 1 ViewModel class for 1 view, but the information for the three views quite similar
    /// </summary>
    public class RestaurantViewModel
    {
        #region Properties
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public int CityID { get; set; }

        [Required]
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string Name { get; set; }

        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string Description { get; set; }
        public string ImageName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Email { get; set; }


        public string CategoryName { get; set; }
        public string CityName { get; set; }
        public bool HasImage { get; set; }
        public string ImagePath { get; set; }
        #endregion

        #region Constructors

        public RestaurantViewModel()
        {
        }
        public RestaurantViewModel(Restaurant dbRestaurant)
        {
            this.CategoryID = dbRestaurant.CategoryID;
            this.CategoryName = dbRestaurant.Category.Name;
            this.CityID = dbRestaurant.CityID;
            this.CityName = dbRestaurant.City.Name;
            this.Name = dbRestaurant.Name;
            this.DateCreated = dbRestaurant.DateCreated;
            this.Description = dbRestaurant.Description;
            this.Email = dbRestaurant.Email;
            this.ID = dbRestaurant.ID;
            this.ImageName = dbRestaurant.ImageName;

            this.HasImage = string.IsNullOrEmpty(dbRestaurant.ImageName) == false;
            if (this.HasImage)
            {
                this.ImagePath = Path.Combine(Constants.ImagesDirectory, this.ImageName);
                string realPath = System.Web.HttpContext.Current.Server.MapPath(this.ImagePath);
                bool isFileExists = File.Exists(realPath);
                if (isFileExists == false)
                {
                    this.ImagePath = Path.Combine(Constants.ImagesDirectory, "FileNotFound.jpg");
                }
            }
        }
        #endregion

        #region public methods
        public void UpdateDbModel(Restaurant dbRestaurant)
        {
            dbRestaurant.CategoryID = this.CategoryID;
            dbRestaurant.CityID = this.CityID;
            dbRestaurant.Name = this.Name;
            dbRestaurant.Description = this.Description;
        }
        #endregion
    }
}

UnitOfWorkSample/Controllers/CommentController.cs
using DataAccess;
using UnitOfWorkSample.Models;
using Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UnitOfWorkSample.Helpers;

namespace UnitOfWorkSample.Controllers
{
    public class CommentController : Controller
    {
        // GET: Category
        [ChildActionOnly]
        public ActionResult CommentsForRestaurant(int restaurantID = 0)
        {
           
            // 1. get all categories from the DB
            UnitOfWork unitOfWork = new UnitOfWork();
            List<Comment> restaurantComments = unitOfWork.CommentRepository.GetAll()
                .Where(c => c.RestaurantID == restaurantID)
                .OrderByDescending(c => c.DateCreated)
                .ToList();

            // initialize the model for the View
            List<CommentViewModel> model = new List<CommentViewModel>();

            // 2. convert all Comment objects to ViewModel objects
            foreach (Comment comment in restaurantComments)
            {
                CommentViewModel newItem = new CommentViewModel(comment);
                model.Add(newItem);
            }

            ViewBag.RestaurantID = restaurantID;

            // 3. pass the viewModel to the view
            return PartialView("_CommentsForRestaurant", model);
        }

        [HttpPost]
        public EmptyResult AddComment(string text, int restaurantID = 0)
        {
            UnitOfWork unitOfWork = new UnitOfWork();

            Comment dbComment = new Comment();
            dbComment.RestaurantID = restaurantID;
            dbComment.UserID = LoginUserSession.Current.UserID;
            dbComment.CommentText = text;
            dbComment.DateCreated = DateTime.Now;

            unitOfWork.CommentRepository.Save(dbComment);
            unitOfWork.Save();
            return new EmptyResult();
        }

        public EmptyResult Delete(int id = 0)
        {
            UnitOfWork unitOfWork = new UnitOfWork();
            unitOfWork.CommentRepository.DeleteByID(id);
            unitOfWork.Save();
            return new EmptyResult();
        }
    }
}

UnitOfWorkSample/Controllers/RestaurantController.cs
using DataAccess;
using UnitOfWorkSample.Helpers;
using UnitOfWorkSample.Models;
using Repositories;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UnitOfWorkSample.Controllers
{
    public class RestaurantController : Controller
    {
        // GET: Restaurant
        public ActionResult Index()
        {
            // if there are some notification message from other actions, then set them in the viewbag
            // so that we display them in the screen
            ViewBag.ErrorMessage = TempData["ErrorMessage"];
            ViewBag.Message = TempData["Message"];

            UnitOfWork unitOfWork = new UnitOfWork();
            List<Restaurant> allRestauraurants = unitOfWork.RestaurantRepository.GetAll();

            List<RestaurantViewModel> model = new List<RestaurantViewModel>();
            foreach (Restaurant dbRestaurant in allRestauraurants)
            {
                RestaurantViewModel restaurantViewModel = new RestaurantViewModel(dbRestaurant);
                model.Add(restaurantViewModel);
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int id = 0)
        {
            // add the Cities to the Viewbag
            CityRepository cityRepository = new CityRepository();
            List<City> allCities = cityRepository.GetAll();
            ViewBag.AllCities = new SelectList(allCities, "ID", "Name");

            // add the Categories to the Viewbag
            UnitOfWork unitOfWork = new UnitOfWork();
            List<Category> allCategories = unitOfWork.CategoryRepository.GetAll();
            ViewBag.AllCategories = new SelectList(allCategories, "ID", "Name");

            // create the viewmodel, based on the Restaurant from the database
            RestaurantViewModel model = new RestaurantViewModel();
            Restaurant dbRestaurant = unitOfWork.RestaurantRepository.GetByID(id);
            if (dbRestaurant != null)
            {
                model = new RestaurantViewModel(dbRestaurant);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(RestaurantViewModel viewModel)
        {
            if (viewModel == null)
            {
                // this should not be possible, but just in case, validate
                TempData["ErrorMessage"] = "Ups, a serious error occured: No Viewmodel.";
                return RedirectToAction("Index");
            }

            // get the item from the database by ID
            UnitOfWork unitOfWork = new UnitOfWork();
            Restaurant dbRestaurant = unitOfWork.RestaurantRepository.GetByID(viewModel.ID);

            // if there is no object in the DB, this is a new item -> will create a new one
            if (dbRestaurant == null)
            {
                dbRestaurant = new Restaurant();
                dbRestaurant.DateCreated = DateTime.Now;
            }

            // update the DB object from the viewModel 
            viewModel.UpdateDbModel(dbRestaurant);

            // save the image to the local folder if there is an uploaded image
            // we have to generate a unique file name, to avoid duplication when the same image is uploaded for another restaurant
            if (Request.Files.Count > 0)
            {
                HttpPostedFileBase file = Request.Files[0];
                // check if the uploaded file is a valid file and only then proceed
                if (file.ContentLength > 0 && string.IsNullOrEmpty(file.FileName) == false)
                {
                    string imagesPath = Server.MapPath(Constants.ImagesDirectory);
                    string uniqueFileName = string.Format("{0}_{1}", DateTime.Now.Ticks, file.FileName);
                    string savedFileName = Path.Combine(imagesPath, Path.GetFileName(uniqueFileName));
                    file.SaveAs(savedFileName);
                    dbRestaurant.ImageName = uniqueFileName;
                }
            }

            unitOfWork.RestaurantRepository.Save(dbRestaurant);
            unitOfWork.Save();

            TempData["Message"] = "The restaurant was saved successfully";
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id = 0)
        {
            UnitOfWork unitOfWork = new UnitOfWork();
            
            bool isDeleted = false;

            Restaurant dbRestaurant = unitOfWork.RestaurantRepository.GetByID(id);
            if (dbRestaurant != null)
            {
                foreach (Comment comment in dbRestaurant.Comments.ToList())
                {
                    unitOfWork.CommentRepository.Delete(comment);
                }
                unitOfWork.RestaurantRepository.Delete(dbRestaurant);
                isDeleted = unitOfWork.Save() > 0;
            }

            if (isDeleted == false)
            {
                TempData["ErrorMessage"] = "Could not find a restaurant with ID = " + id;
            }
            else
            {
                TempData["Message"] = "The restaurant was deleted successfully";
            }

            return RedirectToAction("Index");
        }

        public ActionResult Details(int id = 0)
        {
            UnitOfWork unitOfWork = new UnitOfWork();

            // get the DB object
            Restaurant dbRestaurant = unitOfWork.RestaurantRepository.GetByID(id);
            if (dbRestaurant == null)
            {
                // when we have RedirectToAction, we can not use Viewbag - so we use a TempData!
                TempData["ErrorMessage"] = "Could not find a restaurant with ID = " + id;
                return RedirectToAction("Index");
            }
            else
            {
                // create the view model
                RestaurantViewModel model = new RestaurantViewModel(dbRestaurant);
                return View(model);
            }
        }
    }
}

UnitOfWorkSample/Views/Restaurant/Details.cshtml
@using UnitOfWorkSample.Models
@model RestaurantViewModel

@{
    ViewBag.Title = "Details";
}

@section javascript
{
    <script>
        $("document").ready(function () {
            $("#addComment").click(function () {
                $("#txtNewComment").val("");
                $("#divAddComment").show();
            });

            $("#btnCancelComment").click(function () {
                $("#divAddComment").hide();
            });

            $("#btnSaveComment").click(function () {
                $.post("/Comment/AddComment", {
                    text: $("#txtNewComment").val()
                    , restaurantID: $("#hdnRestaurantID").val()
                })
                .done(function (data) {
                    alert("Your comment was added successfully!");
                    window.location.reload();
                })
                .fail(function () {
                    alert("failed to add comment");
                });
            });

            $(".delComment").click(function () {
                $.post("/Comment/Delete", {
                    id: $(this).attr("data-comment-id")
                })
                .done(function (data) {
                    window.location.reload();
                })
                .fail(function () {
                    alert("failed to delete comment");
                });
            });
    });
    </script>
}

<h2>Details</h2>

<div class="form-horizontal">
    <div class="form-group">
        <label class="control-label col-md-2" for="">Image</label>
        <div class="col-md-10">
            @if (Model.HasImage)
            {
                <img src="@Url.Content(Model.ImagePath)" width="300" alt="Image for @Model.Name" />
            }
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="CategoryID">Category</label>
        <div class="col-md-10">
            @Model.CategoryName
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="CityID">City</label>
        <div class="col-md-10">
            @Model.CityName
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="Name">Name</label>
        <div class="col-md-10">
            @Model.Name
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="Description">Description</label>
        <div class="col-md-10">
            @Model.Description
        </div>
    </div>
</div>

@Html.Action("CommentsForRestaurant", "Comment", new { restaurantID = Model.ID })

UnitOfWorkSample/Views/Restaurant/Edit.cshtml
@using UnitOfWorkSample.Models
@model RestaurantViewModel

@{
    ViewBag.Title = "Edit";
}

@if (Model.ID == 0)
{
    <h2>Create Restaurant</h2>
}
else
{
    <h2>Edit Restaurant</h2>
}

@using (Html.BeginForm("Edit", "Restaurant", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-horizontal">
        <hr />
        @Html.HiddenFor(model => model.ID)


        <div class="form-group">
            <label class="control-label col-md-2" for="">Image</label>
            <div class="col-md-10">
                @if (Model.HasImage)
                {
                    <img src="@Url.Content(Model.ImagePath)" width="300" alt="Image for @Model.Name" />
                }
                <input type="file" name="imageToUpload" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2" for="CategoryID">Category</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryID, (IEnumerable<SelectListItem>)ViewBag.AllCategories, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="CityID">City</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CityID, (IEnumerable<SelectListItem>)ViewBag.AllCities, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Name">Name</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Description">Description</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Index", null,  new { @class= "btn btn-default" })
            </div>
        </div>
    </div>
}

<div>
</div>

UnitOfWorkSample/Views/Restaurant/Index.cshtml
@using UnitOfWorkSample.Models
@model List<RestaurantViewModel>

@{
    ViewBag.Title = "Restaurants";
}

<h2>Restaurants</h2>

@* show ErrorMessage or InfoMessage (usually when we delete/edit/etc.) *@
@Html.Partial("_InfoMessages")


<div class="table-actions">
    @Html.ActionLink("Add New Restaurant", "Edit", "Restaurant", null, new { @class = "btn btn-primary btn-sm" })
</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Has Image</th>
            <th>Name</th>
            <th>Description</th>
            <th>City Name</th>
            <th>Category Name</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    @foreach (RestaurantViewModel restaurant in Model)
    {
        <tr>
            <td>@(restaurant.HasImage ? "Yes" : "No")</td>
            <td>@restaurant.Name</td>
            <td>@restaurant.Description</td>
            <td>@restaurant.CityName</td>
            <td>@restaurant.CategoryName</td>
            <td class="cell-small">
                @Html.ActionLink("Edit", "Edit", "Restaurant", new { id = restaurant.ID }, new { @class = "btn btn-primary btn-sm" })
            </td>
            <td class="cell-small">
                @Html.ActionLink("Delete", "Delete", "Restaurant", new { id = restaurant.ID }, new { onclick = "return confirm('Are you sure you to delete this restaurant?');", @class = "btn btn-danger btn-sm" })
            </td>
        </tr>
    }
</table>