UnitOfWorkSample/Controllers/CategoryController.cs
using DataAccess;
using UnitOfWorkSample.Models;
using Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UnitOfWorkSample.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        public ActionResult Index()
        {
            // if there are some notification message from other actions, then set them in the viewbag
            // so that we display them in the screen
            ViewBag.ErrorMessage = TempData["ErrorMessage"];
            ViewBag.Message = TempData["Message"];

            // 1. get all categories from the DB
            UnitOfWork unitOfWork = new UnitOfWork();
            List<Category> allCategories = unitOfWork.CategoryRepository.GetAll();

            // initialize the model for the View
            List<CategoryViewModel> model = new List<CategoryViewModel>();

            // 2. convert all Category objects to ViewModel objects
            foreach (Category category in allCategories)
            {
                CategoryViewModel newItem = new CategoryViewModel(category);
                model.Add(newItem);
            }

            // 3. pass the viewModel to the view
            return View(model);
        }

        public ActionResult Edit(int id = 0)
        {
            // get the Category to edit
            UnitOfWork unitOfWork = new UnitOfWork();
            Category category = unitOfWork.CategoryRepository.GetByID(id);

            CategoryViewModel model = new CategoryViewModel();
            if (category != null)
            {
                // create the viewModel from the Category
                model = new CategoryViewModel(category);

            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(CategoryViewModel categoryEdit)
        {
            // find the Category in the DB
            UnitOfWork unitOfWork = new UnitOfWork();
            Category dbCategory = unitOfWork.CategoryRepository.GetByID(categoryEdit.ID);

            // if there is no object in the DB, this is a new item -> will create a new one
            if (dbCategory == null)
            {
                dbCategory = new Category();
            }

            // update the DB object from the viewModel 
            categoryEdit.UpdateDbModel(dbCategory);

            unitOfWork.CategoryRepository.Save(dbCategory);
            unitOfWork.Save();

            TempData["Message"] = "The category was saved successfully";
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            UnitOfWork unitOfWork = new UnitOfWork();
            unitOfWork.CategoryRepository.DeleteByID(id);
            bool isDeleted = unitOfWork.Save() > 0;

            if (isDeleted == false)
            {
                TempData["ErrorMessage"] = "Could not find a category with ID = " + id;
            }
            else
            {
                TempData["Message"] = "The category was deleted successfully";
            }

            return RedirectToAction("Index");
        }
    }
}

UnitOfWorkSample/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UnitOfWorkSample.Controllers
{
    public class CityController : Controller
    {
        // GET: City
        public ActionResult Index()
        {
            return View();
        }
    }
}

UnitOfWorkSample/Controllers/RestaurantController.cs
using DataAccess;
using UnitOfWorkSample.Helpers;
using UnitOfWorkSample.Models;
using Repositories;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UnitOfWorkSample.Controllers
{
    public class RestaurantController : Controller
    {
        // GET: Restaurant
        public ActionResult Index()
        {
            // if there are some notification message from other actions, then set them in the viewbag
            // so that we display them in the screen
            ViewBag.ErrorMessage = TempData["ErrorMessage"];
            ViewBag.Message = TempData["Message"];

            UnitOfWork unitOfWork = new UnitOfWork();
            List<Restaurant> allRestauraurants = unitOfWork.RestaurantRepository.GetAll();

            List<RestaurantViewModel> model = new List<RestaurantViewModel>();
            foreach (Restaurant dbRestaurant in allRestauraurants)
            {
                RestaurantViewModel restaurantViewModel = new RestaurantViewModel(dbRestaurant);
                model.Add(restaurantViewModel);
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int id = 0)
        {
            // add the Cities to the Viewbag
            CityRepository cityRepository = new CityRepository();
            List<City> allCities = cityRepository.GetAll();
            ViewBag.AllCities = new SelectList(allCities, "ID", "Name");

            // add the Categories to the Viewbag
            UnitOfWork unitOfWork = new UnitOfWork();
            List<Category> allCategories = unitOfWork.CategoryRepository.GetAll();
            ViewBag.AllCategories = new SelectList(allCategories, "ID", "Name");

            // create the viewmodel, based on the Restaurant from the database
            RestaurantViewModel model = new RestaurantViewModel();
            Restaurant dbRestaurant = unitOfWork.RestaurantRepository.GetByID(id);
            if (dbRestaurant != null)
            {
                model = new RestaurantViewModel(dbRestaurant);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(RestaurantViewModel viewModel)
        {
            if (viewModel == null)
            {
                // this should not be possible, but just in case, validate
                TempData["ErrorMessage"] = "Ups, a serious error occured: No Viewmodel.";
                return RedirectToAction("Index");
            }

            // get the item from the database by ID
            UnitOfWork unitOfWork = new UnitOfWork();
            Restaurant dbRestaurant = unitOfWork.RestaurantRepository.GetByID(viewModel.ID);

            // if there is no object in the DB, this is a new item -> will create a new one
            if (dbRestaurant == null)
            {
                dbRestaurant = new Restaurant();
                dbRestaurant.DateCreated = DateTime.Now;
            }

            // update the DB object from the viewModel 
            viewModel.UpdateDbModel(dbRestaurant);

            // save the image to the local folder if there is an uploaded image
            // we have to generate a unique file name, to avoid duplication when the same image is uploaded for another restaurant
            if (Request.Files.Count > 0)
            {
                HttpPostedFileBase file = Request.Files[0];
                // check if the uploaded file is a valid file and only then proceed
                if (file.ContentLength > 0 && string.IsNullOrEmpty(file.FileName) == false)
                {
                    string imagesPath = Server.MapPath(Constants.ImagesDirectory);
                    string uniqueFileName = string.Format("{0}_{1}", DateTime.Now.Ticks, file.FileName);
                    string savedFileName = Path.Combine(imagesPath, Path.GetFileName(uniqueFileName));
                    file.SaveAs(savedFileName);
                    dbRestaurant.ImageName = uniqueFileName;
                }
            }

            unitOfWork.RestaurantRepository.Save(dbRestaurant);
            unitOfWork.Save();

            TempData["Message"] = "The restaurant was saved successfully";
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id = 0)
        {
            UnitOfWork unitOfWork = new UnitOfWork();
            
            bool isDeleted = false;

            Restaurant dbRestaurant = unitOfWork.RestaurantRepository.GetByID(id);
            if (dbRestaurant != null)
            {
                foreach (Comment comment in dbRestaurant.Comments.ToList())
                {
                    unitOfWork.CommentRepository.Delete(comment);
                }
                unitOfWork.RestaurantRepository.Delete(dbRestaurant);
                isDeleted = unitOfWork.Save() > 0;
            }

            if (isDeleted == false)
            {
                TempData["ErrorMessage"] = "Could not find a restaurant with ID = " + id;
            }
            else
            {
                TempData["Message"] = "The restaurant was deleted successfully";
            }

            return RedirectToAction("Index");
        }

        public ActionResult Details(int id = 0)
        {
            UnitOfWork unitOfWork = new UnitOfWork();

            // get the DB object
            Restaurant dbRestaurant = unitOfWork.RestaurantRepository.GetByID(id);
            if (dbRestaurant == null)
            {
                // when we have RedirectToAction, we can not use Viewbag - so we use a TempData!
                TempData["ErrorMessage"] = "Could not find a restaurant with ID = " + id;
                return RedirectToAction("Index");
            }
            else
            {
                // create the view model
                RestaurantViewModel model = new RestaurantViewModel(dbRestaurant);
                return View(model);
            }
        }
    }
}

UnitOfWorkSample/Controllers/UserController.cs
using DataAccess;
using UnitOfWorkSample.Models;
using Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UnitOfWorkSample.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            // if there are some notification message from other actions, then set them in the viewbag
            // so that we display them in the screen
            ViewBag.ErrorMessage = TempData["ErrorMessage"];
            ViewBag.Message = TempData["Message"];

            // 1. get all categories from the DB
            UnitOfWork unitOfWork = new UnitOfWork();
            List<User> allUsers = unitOfWork.UserRepository.GetAll();

            // initialize the model for the View
            List<UserViewModel> model = new List<UserViewModel>();

            // 2. convert all User objects to ViewModel objects
            foreach (User user in allUsers)
            {
                UserViewModel newItem = new UserViewModel(user);
                model.Add(newItem);
            }

            // 3. pass the viewModel to the view
            return View(model);
        }

        public ActionResult Edit(int id = 0)
        {
            // get the User to edit
            UnitOfWork unitOfWork = new UnitOfWork();
            User user = unitOfWork.UserRepository.GetByID(id);

            UserViewModel model = new UserViewModel();
            if (user != null)
            {
                // create the viewModel from the User
                model = new UserViewModel(user);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(UserViewModel userEdit)
        {
            // find the User in the DB
            UnitOfWork unitOfWork = new UnitOfWork();
            User dbUser = unitOfWork.UserRepository.GetByID(userEdit.ID);

            // if there is no object in the DB, this is a new item -> will create a new one
            if (dbUser == null)
            {
                dbUser = new User();
            }

            // update the DB object from the viewModel 
            userEdit.UpdateDbModel(dbUser);

            unitOfWork.UserRepository.Save(dbUser);
            unitOfWork.Save();

            TempData["Message"] = "The user was saved successfully";
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            bool isDeleted = false;
            UnitOfWork unitOfWork = new UnitOfWork();

            User dbUser = unitOfWork.UserRepository.GetByID(id);
            if (dbUser != null)
            {
                foreach (Comment comment in dbUser.Comments.ToList())
                {
                    unitOfWork.CommentRepository.Delete(comment);
                }
                unitOfWork.UserRepository.Delete(dbUser);
                isDeleted = unitOfWork.Save() > 0;
            }

            if (isDeleted == false)
            {
                TempData["ErrorMessage"] = "Could not find a user with ID = " + id;
            }
            else
            {
                TempData["Message"] = "The user was deleted successfully";
            }

            return RedirectToAction("Index");
        }
    }
}

UnitOfWorkSample/Views/Shared/_InfoMessages.cshtml
@* Display the messages that added to the ViewBag
This partial view has to be somewhere at the top of the page
We create  a partial view to avoid copy-paste of similar code *@

@{
    if (string.IsNullOrEmpty(ViewBag.ErrorMessage) == false)
    {
        <h3>
            <span class="label label-danger">@ViewBag.ErrorMessage</span>
        </h3>
    }
    if (string.IsNullOrEmpty(ViewBag.Message) == false)
    {
        <h3>
            <span class="label label-success">@ViewBag.Message</span>
        </h3>
    }
}

UnitOfWorkSample/Views/Shared/_Layout.cshtml
@using UnitOfWorkSample.Helpers

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.cycle2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Reservation Center", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <nav class="navbar-collapse collapse">
                <ul class="nav nav-pills nav-justified">
                    <li role="presentation">
                        @Html.ActionLink("Users", "Index", "User")
                    </li>
                    <li role="presentation">
                        @Html.ActionLink("Categories", "Index", "Category")
                    </li>
                    <li role="presentation">
                        @Html.ActionLink("Cities", "Index", "City")
                    </li>
                    <li role="presentation">
                        @Html.ActionLink("Restaurants", "Index", "Restaurant")
                    </li>
                    <li role="presentation">
                        <button type="button" class="btn btn-link" id="btnSearch">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </li>
                    @if (LoginUserSession.Current.IsAuthenticated)
                    {
                        <li>
                            <span class="navbar-name">Hello @LoginUserSession.Current.Username </span>
                        </li>
                    }
                    <li>
                        @if (LoginUserSession.Current.IsAuthenticated)
                        {
                            @Html.ActionLink("Logout", "Logout", "Home")
                        }
                        else
                        {
                            @Html.ActionLink("Login", "Login", "Home")
                        }
                    </li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="navbar" id="formSearch" style="display: none;">
        <div class="container noback">
            @using (Html.BeginForm("Search", "Home", FormMethod.Get)) //todo - create a method for that
            {
                <div class="form-horizontal">
                    <div class="form-group search-control">
                        <div>
                            @Html.TextBox("searchVal", null, new  { placeholder = "Search for", @class="form-control"  })
                            @*<input id="searchVal" name="searchVal" type="text" placeholder="Search for" class="form-control" />*@
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script type="text/javascript">
        $("#btnSearch").on("click", function () {
            $("#formSearch").slideToggle("slow");
        });
    </script>
    @RenderSection("javascript", false)
</body>
</html>